# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - scaling-spoon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ab35da5ceca740e18bbe7dc691f47184 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3969f087de0b445ea4592606231fec24 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ab35da5ceca740e18bbe7dc691f47184 }}/scaling-spoon:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'scaling-spoon'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f0b8339c15394d77816fe7ca74fd4831 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ab35da5ceca740e18bbe7dc691f47184 }}/scaling-spoon:${{ github.sha }}'